# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: hg38
  - /optimizer: adamw
  - /scheduler: cosine_warmup
  - /callbacks: [base, checkpoint]

train:
  monitor: test/loss
  mode: min

task:
  _name_: lm
  loss: 
    _name_: cross_entropy # potentially create a new cross_entropy loss that includes weights for uncertain tokens
    ignore_index: 12 # X token (separate anchor-target pairs)
  torchmetrics: ['perplexity', 'num_tokens']

encoder: null
decoder: null
